### ISSUE TITLE
esp32-hal-spi.c doesn't compile with 3.2.0

### ISSUE THREAD

**Issue by lucadentella** [platformio/platform-espressif32#528]
Hi!

I've recently updated the platform to release 3.2.0 and my code doesnt' compile:

```
C:\Users\luca\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c: In function 'spiTransferBytesNL':
C:\Users\luca\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c:922:39: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
C:\Users\luca\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c:923:40: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
Compiling .pio\build\lolin32\FrameworkArduino\main.cpp.o
                 uint8_t * last_data8 = &last_data;
```

If I revert to 3.1.1, everything works fine.
Thanks

**Comment by valeros** [comment]
Hi @lucadentella ! Is there any chance you have the `-Werror` flag in your configuration?

**Comment by lucadentella** [comment]
Hi @valeros 

thanks! yes, I had -Werror:

```
build_flags =
    -Werror
```

if I comment that flag out, I can compile my code (the error is now a warning):

```
C:\Users\luca\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer 
type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
```

is it an expected behavior? 
Thanks

**Comment by valeros** [comment]
Yes, I guess that's expected behavior. The warning comes from the framework itself and the reason why it's not visible in the Arduino IDE is because they use `-w` flag that suppresses all warnings.

**Comment by Blend3rman** [comment]
@valeros It seems like arduino-esp32 has [fixed this bug in April 2021](https://github.com/espressif/arduino-esp32/pull/4996)? Can this [simple change to `esp-hal-spi.c`](https://github.com/espressif/arduino-esp32/blob/5502879a5b25e5fff84a7058f448be481c0a1f73/cores/esp32/esp32-hal-spi.c#L1116) be applied to the platformio codebase as well?

**Comment by kernelpanic85** [comment]
I have this same issue when compiling with ESPHome and espressif 3.5. I second @Blend3rman, can the simple fix from arduino-esp32 be included in this codebase @valeros?

**Comment by FPMilan** [comment]
Compiling hangs for me also on this warning, is there a solution yet?

**Comment by Jason2866** [comment]
@FPMilan Yes, use latest framework.

**Comment by FPMilan** [comment]
thanks @Jason2866 just rerunning it solved it at some point
