### ISSUE TITLE
arduino-esp32 as a component doesn't compile with version 3.3.0

### ISSUE THREAD

**Issue by florian-fouquet** [platformio/platform-espressif32#586]
Hi,

I'm using arduino-esp32 as a component in espressif32 platform.
Using version 3.2.0, i had no problem with compilation.

When updating to the 3.3.0 PlatformIO espressif32 platform, i got this compilation error :
![image](https://user-images.githubusercontent.com/53573342/126546941-92d19b3e-287c-4a7a-8839-c60c5aac4d16.png)

I replaced the function esp_eth_phy_new_ksz8081 by the suggested one esp_eth_phy_new_ksz8041 and succeed to compile all the arduino-esp32 component.

I don't know if ethernet is still working as my project don't use it.
Apparently, it has been fixed in esp-idf master branch.

### Software versions
Visual Studio Code 1.58.2
PlatformIO Core 5.1.1
PlatformIO Home 3.3.4
PlatformIO Espressif 32 version 3.3.0
arduino-esp32 release 2.0.0-rc1 (Also tried with master branch)

**Comment by valeros** [comment]
Hi @florian-fouquet ! The latest Arduino from master or 2.0.0-rc1 cannot be used as Arduino component, simply because it might not be compatible with the ESP-IDF used with Arduino. Here is the last known working configuration https://github.com/platformio/platform-espressif32/blob/develop/examples/espidf-arduino-wifiscan/platformio.ini
